version: '3.7'
services:
  dynamodb:
    image: amazon/dynamodb-local
    platform: linux/arm64
    container_name: my-dynamodb
    hostname: dynamodb
    restart: always
    volumes:
      - ./db/my-dynamodb-data:/home/dynamodblocal/data
    ports:
      - 8000:8000
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
